[theme]
primaryColor = "#E0583B"
backgroundColor = "#F7F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18181B"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false